### ISSUE TITLE
No longer updates

### ISSUE THREAD

**Issue by MaverickC2** [NullSoldier/serverthrall#12]
Updater is no longer grabbing the latest updates. Are you done working on this script? If so let me know and I will use another solution. Thanks.

**Comment by NullSoldier** [comment]
I'm not actively working on it. I'll come back to it, but right now I'm
working on one other side project.

**Comment by NullSoldier** [comment]
I'm investigating this issue again, but it'll take time to track down. I'm running serverthrall on a local server to test.

**Comment by NullSoldier** [comment]
I'll be monitoring this issue but I'm gonna close this for now until I have a good repro case. Target fix date is before august update.
