### ISSUE TITLE
Ginfo Marker Integration

### ISSUE THREAD

**Issue by iv-mexx** [NullSoldier/serverthrall#13]
Hi, 

just opening up this issue as mentioned in the [reddit thread](https://www.reddit.com/r/ConanExiles/comments/6ilt4s/interactive_map_ginfo_updated_for_the_latest_map/?st=j47cir0j&sh=541e93a4) to keep up the conversation. 

I'd be interested to take a look as soon as you push your local branch.

You said you don't need the firebase REST API - how would you post data to firebase without it? As far as I know there's no Python SDK for firebase (yet?).

**Comment by NullSoldier** [comment]
Great, I'll stay in touch when I have something to show tonight.

As for firebase... firebase accepts web socket connections so you can connect in python, do your handshake, then send websocket packets with the same format to firebase as your browser does.

I looked in my browser and checked the frame format for adding a group and saw this frame. 
<img width="1051" alt="screen shot 2017-06-21 at 2 30 14 pm" src="https://user-images.githubusercontent.com/458976/27407754-897b4cc2-568e-11e7-8abe-d3190487c0a2.png">

**Comment by NullSoldier** [comment]
I had to grab someone at the airport and it took most of my night. I'll get back to you tomorrow!

**Comment by iv-mexx** [comment]
No worries!

**Comment by NullSoldier** [comment]
I'm trying to push all this code up really fast, so I'll  continue working on it afterwards but this is getting live updated from ServerThrall. http://serverthrallapi.herokuapp.com/api/1/characters?secret_key=dbe9bde657b911e799672e85e3268305

The codebase for the API is here, https://github.com/NullSoldier/serverthrallapi/blob/master/api/views.py

It allows registering a server, then accessing the data via the generated private key in the response and sending sync requests using the private key. I'm working on pushing up the server thrall part now.

**Comment by NullSoldier** [comment]
There's a bug I need to fix where it's technically re-creating the character in the API each time. I'm going to change it to preserve the character ids. I just ran around and watched the API online and saw my level go up as I leveled up. Awesome...!

Lemme package and get this apiupload plugin for server thrall online.

**Comment by iv-mexx** [comment]
I guess I will need the server thrall update to test it myself, right?

**Comment by NullSoldier** [comment]
It's not ready yet, but all remaining work will be done here. I've got a guest staying in my office so I haven't had much personal project time. I hack on this guy on my macbook when I get the chance until then.

https://github.com/NullSoldier/serverthrall/pull/14

**Comment by iv-mexx** [comment]
Alright, no need to hurry and no need to justify yourself I just wanted to make sure I understand correctly. Maybe I'll take look at your PR when I get to it!

**Comment by NullSoldier** [comment]
I have a gift for you, I just released version v1.3. It's an early release, but it has character uploading. https://github.com/NullSoldier/serverthrall/blob/master/serverthrall/plugins/apiuploader.py

the release is here, https://github.com/NullSoldier/serverthrall/releases/tag/v1.3

**Comment by NullSoldier** [comment]
Eh, I forgot I checked in the hard coded DB location instead of using server thralls server location configuration. I'll release version v1.35 with a fix for that soon, and building data

**Comment by iv-mexx** [comment]
Ok, I think I can manage that, I'll need to change the SYNC_URL to my local server anyway.

**Comment by iv-mexx** [comment]
I have two different Problems testing:

* I dont know how to connect to my local server 😆 I have tried connecting to localhost:27016, 0.0.0.0:27016 and <my-local-ip>:27016, but none of that works. I have never tried hosting my own server before, so I'm not even sure what I need to do 🤕 
* Serverthrall cant connect to the database, even though I have now entered the correct path (with a wrong path I get another error "unable to open database file"):

```
[serverthrall] Unloading ApiUploader plugin after error
Traceback (most recent call last):
  File "serverthrall\thrall.py", line 49, in start
    plugin.tick()
  File "serverthrall\plugins\intervaltickplugin.py", line 37, in tick
    self.tick_interval()
  File "serverthrall\plugins\apiuploader.py", line 78, in tick_interval
    characters = self.client.get_characters()
  File "serverthrall\conandb\__init__.py", line 37, in get_characters
    for row in connection.cursor().execute(SQL):
DatabaseError: file is encrypted or is not a database
```

**Comment by NullSoldier** [comment]
Can you tell me what the path is that you have as the database url? I'm going to release the patch that just uses the known database location instead of having to hard code it.

As for connecting to your server, you probably need to use the multihome parameter, you can find an example in the sample config in the README here, https://github.com/NullSoldier/serverthrall#example-config

**Comment by NullSoldier** [comment]
I have a discord if you are also interested in joining that, I'm off and on occasionally. https://discord.gg/5dK2TdN

**Comment by iv-mexx** [comment]
Oh, you actually have an example, sorry I've missed that 😆 
I'll try later. 

This is my Database Path:
```
DB_PATH = "D:\Documents\GitHub\serverthrall\\vendor\server\ConanSandbox\Saved\game.db"
```

**Comment by iv-mexx** [comment]
I found the problem: my local sqlite version was too old (3.8.something). I've updated the sqlite3.dll thats used by python and now its working!

I'm already posting positions to our database, but now I'll have to figure out how to convert from the game coordinates to our coordinates 😆

**Comment by NullSoldier** [comment]
I was going to write that transformation function pretty soon. That transformation function is probably in Conan Exiles, so I'm gonna download the mod kit and find it.

**Comment by NullSoldier** [comment]
I pushed up a major new version of serverthrall, you'll need to pull the latest versions of both. The API now stores history of each character, so you can see where characters went on the map. I also removed the public secret concept entirely.

http://serverthrallapi.herokuapp.com/api/4/characters
http://serverthrallapi.herokuapp.com/api/4/characters/1/history

**Comment by NullSoldier** [comment]
This is in PR now, closing this issue.
