### ISSUE TITLE
Server Branch support?

### ISSUE THREAD

**Issue by calmcacil** [NullSoldier/serverthrall#43]
Any chance of getting support for server branch? i.e. testlive?

**Comment by NullSoldier** [comment]
That's easy to do because I actually parse
the steamcmd outfit. I'll do this in the next version v2.0.5

**Comment by calmcacil** [comment]
Sweet, cheers.

**Comment by NullSoldier** [comment]
Assigned this to 2.1 will start on this this week

**Comment by NullSoldier** [comment]
I just added this to v2.0.7. https://github.com/NullSoldier/serverthrall/releases/tag/v2.0.7

ServerThrall can now automatically run your server in testlive mode by setting testlive = true in your serverthrall.config. If the server was not previously running testlive, the server will close and update to the test live branch.  You can find information in the README.
