### ISSUE TITLE
[BUG] Plugin Error?

### ISSUE THREAD

**Issue by THCue** [NullSoldier/serverthrall#49]
Could not find where the logs are but I did take a screenshot. The server has been running for about 1 week no issue till this happen have to restart to get it to work again Hope this help.

https://gyazo.com/f571d0e858c78b05075eca0980f5e0e1

**Comment by NullSoldier** [comment]
I fixed this in the latest version, https://github.com/NullSoldier/serverthrall/releases/tag/v2.0.6
