### ISSUE TITLE
[FEATURE REQUEST] Version Info

### ISSUE THREAD

**Issue by THCue** [NullSoldier/serverthrall#50]
Would be nice to show the version info i.e 2.06 etc maybe in the title bar or somewhere?

**Comment by NullSoldier** [comment]
The version of server thrall? I can do that. I'm gonna work on a new release in preparation for Conan Exiles release date.

**Comment by NullSoldier** [comment]
I added this in the latest release. There is a new version.txt included with every release alongside serverthrall.exe. This file is read in and printed into the console / logs as well. Here is an example for the latest release.

```
[serverthrall] Running version 2.0.7
[serverthrall] Initializing with plugin ServerConfig
[serverthrall] Initializing with plugin UptimeTracker
[serverthrall] Initializing with plugin DownRecovery
[serverthrall] Initializing with plugin ServerUpdater
[serverthrall] Initializing with plugin ApiUploader
[serverthrall] Initializing with plugin DeadManSnitch
[serverthrall] Launching server and waiting for child processes with extra arguments, -nosteamclient -MULTIHOME=192.168.2.18
[serverthrall] Server running successfully
```
