### ISSUE TITLE
Adding support for calling pre/post scripts

### ISSUE THREAD

**Issue by powermates** [NullSoldier/serverthrall#80]
It should be a great idea to call a batch file previously and after the execution.  So we can do things like doing database cleanup and backup to Onedrive, moving logs to another dir, uploading database statistics, etc...
pre-script=...
post-script=...

**Comment by NullSoldier** [comment]
Great idea, I'll add a plugin for this.

I'm going to support Python and Batch scripts. Python will be better because if you write a python script, you can accept the full ServerThrall API and get a lot of powerful information. Batch will work too.

**Comment by NullSoldier** [comment]
This is ready for 2.1.7 but I'm doing you one better, when your scripts run, if they provide anything to STDOUT that will be sent to a discord channel if you have that enabled. I use this to run reports, and then ping that into a private discord channel only my admins can see.

**Comment by NullSoldier** [comment]
https://github.com/NullSoldier/serverthrall/pull/89

**Comment by NullSoldier** [comment]
Tested and works. You can have the results of the script sent to discord if you like. This works completely.
